version: '3.8'

services:
  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - 9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./sindy-volume/elasticsearch/data:/usr/share/elasticsearch/data

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - 6379

  graphql_server:
    build: .
    container_name: graphql-server
    env_file:
      - .env
    ports:
      - $PORT:$PORT

volumes:
  sindy-volume:
    name: sindy-volume
